version: '3'
services:
  main:
    image: golang:1.17
    ports:
      - "3000:3000"
    user: "$UID"
    command: go run /app/src/main.go
    working_dir: /app
    volumes:
      - .:/app
      - go-pkg/:/go
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: docker
      POSTGRES_PASSWORD: docker
      PGDATA : /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  go-pkg:
  pg-data:  